[package]
name = "dqn_chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
crossterm = "0.27.0"
csv = "1.3.0"
rand = "0.8.5"
serde = "1.0.193"
tch = "0.14.0"
